handshake timeout
gliderlabs/ssh pull request #204
Opened 2023-06-05 17:40 UTC by aderouineau

This adds support to time out a connection if a successful handshake has not happened within the duration `HandshakeTimeout`.

2023-06-08 00:22 UTC, progrium commented
seems ok to me

2023-10-04 16:54 UTC, gustavosbarreto requested changes
@aderouineau

Can you please elaborate more in the commit message like you did in PR message?
Also, it would be nice to have a unit test for this.

2024-04-19 23:43 UTC, aderouineau commented
@gustavosbarreto Added a unit test and reworded the commit message.

2024-12-16 04:42 UTC, aderouineau commented
@belak @gustavosbarreto This PR has been sitting for 6 months now. Does anything else need to be addressed, or can it be merged?

2025-01-27 22:38 UTC, merged

2025-03-28 17:52 UTC, aderouineau commented
@gustavosbarreto When do you plan on creating a new release version that will include this change?